TestingSystem/TestingSystem.Website/Controllers/Admin/AnswerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using TestingSystem.Common.Interfaces;
using TestingSystem.Model;

namespace TestingSystem.Website.Controllers.Admin
{
    [Authorize(Roles = "admin")]
    public class AnswerController : Controller
    {
        private readonly IRepository<Question> _questionRepository;
        private readonly IRepository<Answer> _answerRepository;

        public AnswerController(IRepository<Question> question, IRepository<Answer> answer)
        {
            _questionRepository = question;
            _answerRepository = answer;
        }

        public ActionResult Create(int? questionId)
        {
            if (questionId != null)
            {
                Question question = _questionRepository.GetById((int)questionId);
                if (question != null)
                    ViewBag.QuestionId = new SelectList(new List<Question> {question}, "Id", "Text");
                else
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }            
            else
                ViewBag.QuestionId = new SelectList(_questionRepository.GetAll().ToList(), "Id", "Text");

            ViewBag.UrlReferrer = Request.UrlReferrer?.ToString();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(string urlReferrer, Answer answer)
        {
            if (ModelState.IsValid)
            {
                _answerRepository.Create(answer);
                _answerRepository.Save();
                if (!String.IsNullOrEmpty(urlReferrer))
                    return Redirect(urlReferrer);
                return RedirectToAction("Index", "Question");
            }
            if (!String.IsNullOrEmpty(urlReferrer))
                ViewBag.UrlReferrer = urlReferrer;
            ViewBag.QuestionId = new SelectList(_questionRepository.GetAll().ToList(), "Id", "Text", answer.QuestionId);
            return View(answer);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Answer answer = _answerRepository.GetById((int)id);
            if (answer == null)
            {
                return HttpNotFound();
            }

            ViewBag.UrlReferrer = Request.UrlReferrer?.ToString();
            ViewBag.QuestionId = new SelectList(_questionRepository.GetAll().ToList(), "Id", "Text", answer.QuestionId);
            return View(answer);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(string urlReferrer, Answer answer)
        {
            if (ModelState.IsValid)
            {
                _answerRepository.Update(answer);
                _answerRepository.Save();
                if (!String.IsNullOrEmpty(urlReferrer))
                    return Redirect(urlReferrer);
                return RedirectToAction("Index", "Question");
            }
            if (!String.IsNullOrEmpty(urlReferrer))
                ViewBag.UrlReferrer = urlReferrer;
            ViewBag.QuestionId = new SelectList(_questionRepository.GetAll().ToList(), "Id", "Text", answer.QuestionId);
            return View(answer);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Answer answer = _answerRepository.GetById((int)id);
            if (answer == null)
            {
                return HttpNotFound();
            }
            ViewBag.UrlReferrer = Request.UrlReferrer?.ToString();
            return View(answer);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string urlReferrer, int id)
        {
            _answerRepository.Delete(id);
            _answerRepository.Save();
            if (!String.IsNullOrEmpty(urlReferrer))
                return Redirect(urlReferrer);
            return RedirectToAction("Index", "Question");
        }
    }
}

TestingSystem/TestingSystem.Website/Controllers/Admin/QuestionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using System.Web.Mvc.Html;
using PagedList;
using TestingSystem.Common.Interfaces;
using TestingSystem.Model;

namespace TestingSystem.Website.Controllers.Admin
{
    [Authorize(Roles = "admin")]
    public class QuestionController : Controller
    {
        private readonly IRepository<Test> _testRepository;
        private readonly IRepository<Question> _questionRepository;

        public QuestionController(IRepository<Test> test, IRepository<Question> question)
        {
            _testRepository = test;
            _questionRepository = question;
        }

        public ActionResult Index(int? testId, int? questionId, int? page)
        {
            int pageSize = 4;
            int pageNumber = page ?? 1;
            List<Test> tests = new List<Test>() { new Test { Id = 0, Name = "All"} };
            tests.AddRange(_testRepository.GetAll().OrderBy(x => x.Name).ToList());
            ViewBag.TestId = new SelectList(tests, "Id", "Name");
            ViewBag.id = testId;
            ViewBag.qId = questionId;
            if (testId != null && testId != 0)
            {
                Test test = _testRepository.GetById((int)testId);
                if (test != null)
                {
                    return View(test.Questions.OrderBy(x => x.Test.Name).ToPagedList(pageNumber, pageSize));
                }
            }

            return View(_questionRepository.GetAll().OrderBy(x => x.Text).ToPagedList(pageNumber, pageSize));
        }

        public ActionResult Create()
        {
            ViewBag.UrlReferrer = Request.UrlReferrer;
            ViewBag.TestId = new SelectList(_testRepository.GetAll().ToList(), "Id", "Name");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(string urlReferrer, Question question)
        {
            if (ModelState.IsValid)
            {
                _questionRepository.Create(question);
                _questionRepository.Save();
                if (!String.IsNullOrEmpty(urlReferrer))
                    return Redirect(urlReferrer);
                return RedirectToAction("Index");
            }
            if (!String.IsNullOrEmpty(urlReferrer))
                ViewBag.UrlReferrer = urlReferrer;
            ViewBag.TestId = new SelectList(_testRepository.GetAll().ToList(), "Id", "Name", question.TestId);
            return View(question);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Question question = _questionRepository.GetById((int)id);
            if (question == null)
            {
                return HttpNotFound();
            }
            ViewBag.UrlReferrer = Request.UrlReferrer;
            ViewBag.TestId = new SelectList(_testRepository.GetAll().ToList(), "Id", "Name", question.TestId);
            return View(question);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(string urlReferrer, Question question)
        {
            if (ModelState.IsValid)
            {
                _questionRepository.Update(question);
                _questionRepository.Save();
                if (!String.IsNullOrEmpty(urlReferrer))
                    return Redirect(urlReferrer);
                return RedirectToAction("Index");
            }
            if (!String.IsNullOrEmpty(urlReferrer))
                ViewBag.UrlReferrer = urlReferrer;
            ViewBag.TestId = new SelectList(_testRepository.GetAll().ToList(), "Id", "Name", question.TestId);
            return View(question);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Question question = _questionRepository.GetById((int)id);
            if (question == null)
            {
                return HttpNotFound();
            }
            ViewBag.UrlReferrer = Request.UrlReferrer;
            return View(question);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string urlReferrer, int id)
        {
            _questionRepository.Delete(id);
            _questionRepository.Save();
            if (!String.IsNullOrEmpty(urlReferrer))
                return Redirect(urlReferrer);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Select(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            List<Answer> answers = _questionRepository.GetById((int)id).Answers.ToList();
            ViewBag.QuestionId = id;
            return PartialView(answers);
        }
    }
}

TestingSystem/TestingSystem.Website/Views/Question/Create.cshtml
@model TestingSystem.Model.Question

@{
    ViewBag.Title = "Create question";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
	@using (Html.BeginForm())
	{
		@Html.AntiForgeryToken()
		@Html.Hidden("urlReferrer", ViewBag.UrlReferrer as string)

		<div>
			<h4>Question</h4>
			<hr />
			@Html.ValidationSummary(true, "", new { @class = "text-danger" })
			<div class="form-group">
				@Html.LabelFor(model => model.Text, htmlAttributes: new { @class = "col-form-label col-md-2 font-weight-bold" })
				<div class="col-md-6">
					@Html.EditorFor(model => model.Text, new { htmlAttributes = new { @class = "form-control" } })
					@Html.ValidationMessageFor(model => model.Text, "", new { @class = "text-danger" })
				</div>
			</div>

			<div class="form-group">
				@Html.LabelFor(model => model.TestId, "Test", htmlAttributes: new { @class = "col-form-label col-md-2 font-weight-bold" })
				<div class="col-md-6">
					@Html.DropDownList("TestId", null, htmlAttributes: new { @class = "form-control" })
					@Html.ValidationMessageFor(model => model.TestId, "", new { @class = "text-danger" })
				</div>
			</div>
			
			<a class="col-md-6" id="addAnswer" href="">Add answer</a>
			<hr>
			<div id="newAnswer"></div>
			
			<div class="form-group mt-2">
				<div class="col-md-10">
					<input id="save" type="submit" value="Create" class="btn btn-primary" /> |
					<a href="@ViewBag.UrlReferrer" class="btn btn-primary">Back</a>
				</div>
			</div>
		</div>
	}
</div>

<script>
	var i = 0;
	$('#addAnswer').on('click',function(e) {
		var html =`<span class=\"col-md-6 offset\" style=\"font-weight:bold;\">Answer ${i + 1}</span><div class=\"form-group\">
		<label class=\"col-form-label col-md-2 font-weight-bold\" for=\"Answers_${i}__Text\">Text</label>
		<div class=\"col-md-6\"><textarea class=\"form-control text-box multi-line\" data-val=\"true\" 
		data-val-required=\"Required field Text.\" id=\"Answers_${i}__Text\" name=\"Answers[${i}].Text\"></textarea>
		<span class=\"field-validation-valid text-danger\" data-valmsg-for=\"Answers[${i}].Text\" data-valmsg-replace=\"true\"></span> 
		</div></div><div class=\"form-group\"> 
		<label class=\"col-form-label col-md-2 font-weight-bold\" for=\"Answers_${i}__isCorrect\">isCorrect</label> 
		<div class=\"col-md-6\"><div>
		<input class=\"check-box\" data-val=\"true\" data-val-required=\"Required field isCorrect.\" id=\"Answers_${i}__isCorrect\"  
		name=\"Answers[${i}].isCorrect\" type=\"checkbox\" value=\"true\"><input name=\"Answers[${i}].isCorrect\" type=\"hidden\"  
		value=\"false\"><span class=\"field-validation-valid text-danger\" data-valmsg-for=\"Answers[${i}].isCorrect\" 
		 data-valmsg-replace=\"true\"></span></div></div></div><hr>`;
		$("#newAnswer").append(html);
		i++;
		e.preventDefault();
	});
</script>

TestingSystem/TestingSystem.Website/Views/Question/Delete.cshtml
@model TestingSystem.Model.Question

@{
    ViewBag.Title = "Delete question";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
	<h3>Are you sure you want to delete this?</h3>
	<div>
		<h4>Question</h4>
		<hr />
		<dl class="container">
			<dt>
				@Html.DisplayNameFor(model => model.Test.Name)
			</dt>

			<dd>
				@Html.DisplayFor(model => model.Test.Name)
			</dd>

			<dt>
				@Html.DisplayNameFor(model => model.Text)
			</dt>

			<dd>
				@Html.DisplayFor(model => model.Text)
			</dd>

		</dl>

		@using (Html.BeginForm())
		{
			@Html.AntiForgeryToken()
			@Html.Hidden("urlReferrer", ViewBag.UrlReferrer as string)

			<div class="container">
				<input type="submit" value="Delete" class="btn btn-primary" /> |
				<a href="@ViewBag.UrlReferrer" class="btn btn-primary">Back</a>
			</div>
		}
	</div>
</div>

TestingSystem/TestingSystem.Website/Views/Question/Edit.cshtml
@model TestingSystem.Model.Question

@{
    ViewBag.Title = "Edit question";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
	@using (Html.BeginForm())
	{
		@Html.AntiForgeryToken()
		@Html.Hidden("urlReferrer", ViewBag.UrlReferrer as string)

		<div class="container">
			<h4>Question</h4>
			<hr />
			@Html.ValidationSummary(true, "", new { @class = "text-danger" })
			@Html.HiddenFor(model => model.Id)

			<div class="form-group">
				@Html.LabelFor(model => model.Text, htmlAttributes: new { @class = "col-form-label col-md-2 font-weight-bold" })
				<div class="col-md-6">
					@Html.EditorFor(model => model.Text, new { htmlAttributes = new { @class = "form-control" } })
					@Html.ValidationMessageFor(model => model.Text, "", new { @class = "text-danger" })
				</div>
			</div>

			<div class="form-group">
				@Html.LabelFor(model => model.TestId, "Test", htmlAttributes: new { @class = "col-form-label col-md-2 font-weight-bold" })
				<div class="col-md-6">
					@Html.DropDownList("TestId", null, htmlAttributes: new { @class = "form-control" })
					@Html.ValidationMessageFor(model => model.TestId, "", new { @class = "text-danger" })
				</div>
			</div>

			<div class="form-group">
				<div class="col-md-10">
					<input type="submit" value="Save" class="btn btn-primary" /> |
					<a href="@ViewBag.UrlReferrer" class="btn btn-primary">Back</a>
				</div>
			</div>
		</div>
	}
</div>

TestingSystem/TestingSystem.Website/Views/Question/Index.cshtml
@model PagedList.IPagedList<TestingSystem.Model.Question>
@using PagedList.Mvc
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Questions";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var array = new int[Model.Count];
    for (int i = 0; i < Model.Count; i++)
    {
        array[i] = Model[i].Id;
    }
}

<div class="container">
	<h2>Questions</h2>

	<p>
		@Html.ActionLink("Create New", "Create")
	</p>

	<form method="get">
		<div class="form-inline">
			<label class="col-form-label">Test: </label>
			@Html.DropDownList("TestId", null, htmlAttributes: new { @class = "form-control-sm ml-2" })
			<input type="submit" value="Filter" class="btn btn-outline-dark ml-2 btn-sm" />
		</div>
	</form>
	<br />

	<div id="loading" style="display: none; font-weight: bold;">
		<p>Идёт загрузка...</p>
	</div>

	<table class="table" style="word-break: break-all;">
		<tr class="row">
			<th class="col-2">
				Test
			</th>
			<th class="col-7">
				Text
			</th>
			<th class="col-1">
				Answers
			</th>
			<th class="col-2"></th>
		</tr>

		@foreach (var item in Model)
		{
			<tr id="tr_@item.Id" class="row">
				<td class="col-2">
					@Html.DisplayFor(modelItem => item.Test.Name)
				</td>
				<td class="col-7">
					@Html.DisplayFor(modelItem => item.Text)
				</td>
				<td class="col-1">
					@Html.DisplayFor(modelItem => item.Answers.Count)
				</td>
				<td class="col-2">
					<a id="@item.Id" href="">Select</a> |
					@Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
					@Html.ActionLink("Delete", "Delete", new { id = item.Id })
				</td>
			</tr>
		}

	</table>
	<br />
	<div id="selected"></div>
	<br />

	Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

	@Html.PagedListPager(Model, page => Url.Action("Index", new { testId = ViewBag.id, page }))
</div>

<script type="text/javascript">

	@foreach (var item in Model)
	{
		<text>
			$("#@item.Id").on('click', function (e) {
				e.preventDefault();
				$.ajax({
					url: "/Question/Select",
					method: 'POST',
					data: { id: "@item.Id" },
					success: function (data) {
						document.getElementById('loading').style.display = "none";
						$('#selected').html(data);
						document.getElementById('selected').style.display = "block";
						@foreach (var i in Model)
						{
							<text>
								document.getElementById("tr_@i.Id").removeAttribute("style");
							</text>
						}
						document.getElementById("tr_" + e.target.id).setAttribute("style", "background-color: #80b1b2;");
					},
					beforeSend: function () {
						document.getElementById('loading').style.display = "block";
						if (document.getElementById("tr_" + e.target.id).style.backgroundColor === "rgb(128, 177, 178)") {
							document.getElementById("tr_" + e.target.id).removeAttribute("style");
							document.getElementById('loading').style.display = "none";
							document.getElementById('selected').style.display = "none";
							this.abort();
						}
					},
					error: function() {
						document.getElementById('loading').style.display = "none";
					}
				});
				e.preventDefault();
			});
		</text>
	}
</script>

TestingSystem/TestingSystem.Website/Views/Question/Select.cshtml
@model IEnumerable<TestingSystem.Model.Answer>

<h4>Answers</h4>
<p>
    @Html.ActionLink("Create New", "Create", "Answer", new { questionId = ViewBag.QuestionId }, null)
</p>
<table class="table" style="word-break: break-all;">
    <tr class="row">
        <th class="col-8">
            @Html.DisplayNameFor(model => model.Text)
        </th>
        <th class="col-2">
            @Html.DisplayNameFor(model => model.isCorrect)
        </th>
        <th class="col-2"></th>
    </tr>

    @foreach (var item in Model) {
        <tr class="row">
            <td class="col-8">
                @Html.DisplayFor(modelItem => item.Text)
            </td>
            <td class="col-2">
                @Html.DisplayFor(modelItem => item.isCorrect)
            </td>
            <td class="col-2">
                @Html.ActionLink("Edit", "Edit", "Answer", new { id=item.Id }, null) |
                @Html.ActionLink("Delete", "Delete", "Answer", new { id=item.Id }, null)
            </td>
        </tr>
    }

</table>